stages:
- build_debug
- cleanup


cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

cleanup_build_job:
  stage: cleanup
  script:
    - gradle clean
  when: on_failure


build_job:
  stage: build_debug
  script: 
    - export storeFile=/home/key/debug-keystore.jks
    - export storePassword=123456
    - export keyAlias=leap123.debug
    - export keyPassword=123456
    - git submodule init
    - git submodule sync 
    - git submodule update
    - gradle assembleDebug
  artifacts:
    paths:
         - app/build/outputs/apk/*debug*